# Generated by Django 4.2.4 on 2023-11-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(max_length=80)),
                ('fono', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('numeroPersonas', models.IntegerField()),
                ('correo', models.EmailField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
