# Generated by Django 4.2.4 on 2023-11-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReserva', models.IntegerField()),
                ('nombrePersona', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('numeroPersonas', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
